**CREATING** **TENSORS**

Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

In [ ]:
import torch

In [ ]:
torch.__version__

'2.2.1+cu121'

**SCALER** **OPERATION**

In [ ]:
scaler = torch.tensor(3)
scaler

tensor(3)

In [ ]:
scaler.ndim

0

In [ ]:
scaler.shape

torch.Size([])

In [ ]:
scaler.item()

3

**VECTOR** **OPERATION**

In [ ]:
vector = torch.tensor([2,4])
vector

tensor([2, 4])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
item = vector[0]
print(item)

tensor(2)


In [ ]:
item = vector[1]
item

tensor(4)

**MATRIX** **OPERATION**

In [ ]:
MATRIX = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
MATRIX

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [11, 12, 13]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([4, 3])

In [ ]:
item = MATRIX[0,0]
item

tensor(1)

In [ ]:
item = MATRIX[1,2]
item

tensor(6)

**TENSOR** **OPERATION**

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9],[11,12,13]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [11, 12, 13]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 4, 3])

In [ ]:
item = TENSOR[0,0]
item

tensor([1, 2, 3])

In [ ]:
item = TENSOR[0,1]
item

tensor([4, 5, 6])

In [ ]:
item = TENSOR[0,0,0]
item

tensor(1)

In [ ]:
item = TENSOR[0,0,2]
item

tensor(3)

**RANDOM** **TENSORS**

 Machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

 **Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers.........**

 As a data scientist, you can define how the machine learning model starts (**initialization**), looks at data (**representation**) and updates (**optimization**) its random numbers.

In [ ]:
#how to create a tensor of random numbers

random_tensor = torch.rand(size=(4,3))
random_tensor

tensor([[0.0300, 0.9139, 0.5865],
        [0.9665, 0.8596, 0.8997],
        [0.3863, 0.7629, 0.3649],
        [0.3494, 0.9017, 0.2615]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
# We wanted a random tensor in the common image shape of [224, 224, 3] ([height, width, color_channels]).

image_random = torch.rand(size=(224, 224, 3))

In [ ]:
image_random

In [ ]:
image_random.ndim

3

**Zeros and Ones**

Sometimes you'll just want to fill tensors with zeros or ones.

This happens a lot with **masking** (like masking some of the values in one tensor with zeros to let a model know not to learn them).

In [ ]:
# create a tensor full of zeros

tensor_zero = torch.zeros(size=(4,3))
tensor_zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# create a tensor of all ones

tensor_one = torch.ones(size=(4,3))
tensor_one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

**Creating a range and tensors like**

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use **torch.arange(start, end, step)** to do so.

In [ ]:
tensor_range1 = torch.range(0,10)

<ipython-input-44-5d46a607556d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tensor_range1 = torch.range(0,10)


In [ ]:
tensor_range2 = torch.arange(start=0,end=10,step=1)
tensor_range2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor_range3 = torch.arange(0,10,3)
tensor_range3

tensor([0, 3, 6, 9])

Sometimes you might want **one tensor of a certain type with the same shape as another tensor.**

**For example**, a tensor of all zeros with the same shape as a previous tensor.

To do so you can use **torch.zeros_like(input)** or **torch.ones_like(input)** which return a tensor filled with zeros or ones in the same shape as the input respectively.

In [ ]:
# Can also create a tensor of zeros similar to another tensor

tensor_range4 = torch.zeros_like(input=tensor_range3)
tensor_range4

tensor([0, 0, 0, 0])

In [ ]:
tensor_range5 = torch.ones_like(input=tensor_range2)
tensor_range5

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**Tensor datatypes**

In [ ]:
# how to create some tensors with specific datatypes. We can do so using the dtype parameter.
# requires_grad=True ,if True, operations performed on the tensor are recorded
# Default datatype for tensors is float32

tensor_32_datatype = torch.tensor([1.0,2.0,3.0], dtype=None, device=None, requires_grad=False)

In [ ]:
tensor_32_datatype.shape

torch.Size([3])

In [ ]:
tensor_32_datatype.dtype

torch.float32

In [ ]:
tensor_32_datatype.device

device(type='cpu')

In [ ]:
#cpu, cuda, ipu, xpu

tensor_16_datatype  = torch.tensor([2.0,3.0,4.0], dtype=torch.float64, device='cpu')

**Getting information from tensors**

shape - what shape is the tensor? (some operations require specific shape rules)

dtype - what datatype are the elements within the tensor stored in?

device - what device is the tensor stored on? (usually GPU or CPU)

In [ ]:
#create a random tensor and find out details about it.

random_tensor = torch.rand(size=(4,4))

random_tensor

tensor([[0.4518, 0.5337, 0.5246, 0.6502],
        [0.7720, 0.9557, 0.8361, 0.4819],
        [0.2481, 0.7361, 0.3845, 0.5265],
        [0.4870, 0.3354, 0.6849, 0.9643]])

In [ ]:
print(random_tensor)
print(f"Shape of my tensor: {random_tensor.shape}")
print(f"Datatype of my tensor: {random_tensor.dtype}")
print(f"Device of my tensor: {random_tensor.device}")

tensor([[0.4518, 0.5337, 0.5246, 0.6502],
        [0.7720, 0.9557, 0.8361, 0.4819],
        [0.2481, 0.7361, 0.3845, 0.5265],
        [0.4870, 0.3354, 0.6849, 0.9643]])
Shape of my tensor: torch.Size([4, 4])
Datatype of my tensor: torch.float32
Device of my tensor: cpu


In [ ]:
random_tensor = torch.rand(size=(1,5,4))

random_tensor

tensor([[[0.0395, 0.6655, 0.9903, 0.1457],
         [0.5824, 0.4585, 0.3655, 0.3138],
         [0.6218, 0.3728, 0.1447, 0.0215],
         [0.7849, 0.6297, 0.2383, 0.6260],
         [0.9617, 0.2675, 0.4063, 0.2266]]])

In [ ]:
random_tensor = torch.rand(size=(2,5,4))

random_tensor

tensor([[[0.9947, 0.3326, 0.3801, 0.1499],
         [0.0020, 0.3424, 0.1981, 0.9365],
         [0.1528, 0.7981, 0.4715, 0.6367],
         [0.8017, 0.1987, 0.8065, 0.2956],
         [0.5533, 0.5546, 0.3039, 0.6273]],

        [[0.2901, 0.6695, 0.0086, 0.2481],
         [0.4263, 0.4104, 0.7993, 0.7504],
         [0.4171, 0.0520, 0.6573, 0.6732],
         [0.2493, 0.0617, 0.4215, 0.1851],
         [0.5907, 0.0967, 0.4709, 0.7191]]])

In [ ]:
item_random_tensor = random_tensor[0,0]
item_random_tensor

tensor([0.9947, 0.3326, 0.3801, 0.1499])

In [ ]:
item_random_tensor = random_tensor[1,0]
item_random_tensor

tensor([0.2901, 0.6695, 0.0086, 0.2481])

In [ ]:
item_random_tensor = random_tensor[1,0,3]
item_random_tensor

tensor(0.2481)

**Manipulating Tensors (tensor operations)**

In deep learning, data (images, text, video, audio, protein structures, etc) gets represented as tensors.

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are :

**Addition**

**Substraction**

**Multiplication (element-wise)**

**Division**

**Matrix multiplication**

In [ ]:
#Addition

Add_tensor = torch.tensor(1)
Add_tensor + 10

tensor(11)

In [ ]:
Add_tensor

tensor(1)

In [ ]:
Add_tensor + 20

tensor(21)

In [ ]:
Add_tensor = torch.tensor([1,2,3,3,4])
Add_tensor + 10

tensor([11, 12, 13, 13, 14])

In [ ]:
Add_tensor = torch.tensor([[1,2,3],[4,5,6]])
Add_tensor + 10

tensor([[11, 12, 13],
        [14, 15, 16]])

In [ ]:
# Notice how the tensor values above didn't end up being tensor([[110, 120, 130],[140,150,160]]),
#this is because the values inside the tensor don't change unless they're reassigned.

Add_tensor * 10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [ ]:
# Tensors don't change unless reassigned

Add_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Substract and reassign

sub_tensor = Add_tensor - 4
sub_tensor

tensor([[-3, -2, -1],
        [ 0,  1,  2]])

In [ ]:
# ADD and reassign

ad_tensor = sub_tensor + 4
ad_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
mul_tensor = ad_tensor * 10
mul_tensor

tensor([[10, 20, 30],
        [40, 50, 60]])

In [ ]:
mul_tensor/10

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
# PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.

a = torch.tensor([1,2,3])
torch.add(a, 10)

tensor([11, 12, 13])

In [ ]:
torch.mul(a,10)

tensor([10, 20, 30])

In [ ]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)

print(a*a)

tensor([1, 4, 9])


**MATRIX** **MULTIPLICATION**

PyTorch implements matrix multiplication functionality in the **torch.matmul()** method.

The main **two rules for matrix multiplication** to remember are:

The **inner dimensions** must match:

(3, 2) @ (3, 2) won't work

(2, 3) @ (3, 2) will work

(3, 2) @ (2, 3) will work


The resulting matrix has the **shape of the outer dimensions**:

(2, 3) @ (3, 2) -> (2, 2)

(3, 2) @ (2, 3) -> (3, 3)


In [ ]:
# Let's create a tensor and perform element-wise multiplication and matrix multiplication on it.

b = torch.tensor([1,2,3])

In [ ]:
# Element-wise matrix multiplication
# Element-wise multiplication	[1*1, 2*2, 3*3] = [1, 4, 9]	(tensor * tensor)

b * b

tensor([1, 4, 9])

In [ ]:
# Matrix multiplication	[1*1 + 2*2 + 3*3] = [14]	tensor.matmul(tensor)

torch.matmul(b,b)

tensor(14)

In [ ]:
b @ b

tensor(14)

In [ ]:
# You can do matrix multiplication by hand but it's not recommended.
# The in-built torch.matmul() method is faster.
# b= torch.tensor([1,2,3])
%%time

value = 0
for i in range(len(b)) :
  value += b[i] * b[i]

value

CPU times: user 404 µs, sys: 0 ns, total: 404 µs
Wall time: 413 µs


tensor(14)

In [ ]:
%%time

torch.matmul(b,b)

CPU times: user 2.01 ms, sys: 0 ns, total: 2.01 ms
Wall time: 14.2 ms


tensor(14)

**One of the most common errors in deep learning (shape errors)**

In [ ]:
import torch

In [ ]:
x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]], dtype=torch.float32)


y = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]], dtype=torch.float32)

torch.matmul(x,y)

tensor([[ 30.,  36.,  42.],
        [ 66.,  81.,  96.],
        [102., 126., 150.]])

In [ ]:
# We can make matrix multiplication work between x and y by making their inner dimensions match.

# One of the ways to do this is with a transpose (switch the dimensions of a given tensor).


x = torch.tensor([[1,2],
                  [4,5],
                  [7,8]], dtype=torch.float32)


y = torch.tensor([[1,2],
                  [4,5],
                  [7,8]], dtype=torch.float32)

# torch.matmul(x,y)  ----   RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
# MATRIX TRANSPOSE OPERATION
# torch.transpose(input,dimo,dim1)
# tensor.T -----  where tensor is the desired tensor to transpose.

y = torch.tensor([[1,2],
                  [4,5],
                  [7,8]], dtype=torch.float32)

# torch.transpose(y,0,1) or y.T
y_new_matrix = y.T

In [ ]:
y_new_matrix

tensor([[1., 4., 7.],
        [2., 5., 8.]])

In [ ]:
torch.matmul(x,y_new_matrix)

tensor([[  5.,  14.,  23.],
        [ 14.,  41.,  68.],
        [ 23.,  68., 113.]])

In [ ]:
torch.mm(x,y_new_matrix)

tensor([[  5.,  14.,  23.],
        [ 14.,  41.,  68.],
        [ 23.,  68., 113.]])

**NEURAL NETWORKS BASICS**

In [ ]:
# Neural networks are full of matrix multiplications and dot products.

# The torch.nn.Linear() module, also known as a feed-forward layer or fully connected layer,
# implements a matrix multiplication between an input x and a weights matrix W.

#    Y = X.W + b     ---- Y = output patterns, X = input to the layer,
#  w = weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data.
# b = bias term used to slightly offset the weights and inputs.

# # Since the linear layer starts with a random weights matrix, let's make it reproducible.

# in_features = matches inner dimension of input
# out_features = describes outer value


In [ ]:
# Input Shape

A = torch.tensor([[1,2,3],
                 [4,5,6]], dtype=torch.float32)

A.shape

torch.Size([2, 3])

In [ ]:
linear = torch.nn.Linear(in_features=3, out_features=6)

In [ ]:
# Output Shape

output = linear(A)    # y = linear (x) + b

print(output.shape)
print(output)

torch.Size([2, 6])
tensor([[-0.2065,  0.1095, -1.5169,  1.7267,  0.7022, -0.5307],
        [-0.3153,  1.3053, -2.4071,  3.6037, -0.1537, -1.7647]],
       grad_fn=<AddmmBackward0>)


**Finding the min, max, mean, sum, etc (aggregation)**

In [ ]:
# create a tensor

T = torch.arange(1,100,5)
T

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81, 86,
        91, 96])

In [ ]:
# T.min()

print(f"Minimum No:{T.min()}")
print(f"Maximum No:{T.max()}")


# print(f"Mean:{T.mean()}") #ERROR

print(f"Mean:{T.type(torch.float32).mean()}")

print(f"Sum:{T.sum()}")

Minimum No:1
Maximum No:96
Mean:48.5
Sum:970


In [ ]:
torch.min(T)

tensor(1)

In [ ]:
torch.mean(T.type(torch.float32))

tensor(48.5000)

**Positional min/max**

You can also **find the index of a tensor** where the max or minimum occurs with **torch.argmax() and torch.argmin()** respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself

In [ ]:
T1 = torch.arange(10,100,10)
print(T1)

print(f"Minimum value at index: {T1.argmin()}")

print(f"Maximum value at index: {T1.argmax()}")


tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Minimum value at index: 0
Maximum value at index: 8


**Change tensor datatype**

Common issue with deep learning operations is having your **tensors in different datatypes**.

If one tensor is in **torch.float64** and another is in **torch.float32**, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using **tensor.type(dtype=None)** where the dtype parameter is the datatype you'd like to use.

In [ ]:
T2 = torch.arange(1,10,2)
print(T2)
T2.dtype

tensor([1, 3, 5, 7, 9])


torch.int64

In [ ]:
T3 = T2.type(torch.float16)
print(T3)
T3.dtype

tensor([1., 3., 5., 7., 9.], dtype=torch.float16)


torch.float16

**Reshaping**, **stacking**, **squeezing and unsqueezing**

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

In [ ]:
import torch

z = torch.arange(1.,10.)

print(z)
print(z.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9])


In [ ]:
# # Add an extra dimension

z_reshape = z.reshape(1,9)

print(z_reshape)
print(z_reshape.shape)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])


In [ ]:
# Remove extra dimension from z_reshape

z_remove_dim = z_reshape.squeeze()

print(z_remove_dim)
print(z_remove_dim.shape)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([9])


In [ ]:
## Add an extra dimension with unsqueeze
## use torch.unsqueeze() to add a dimension value of 1 at a specific index.


z_unsqueeze = z_remove_dim.unsqueeze(dim=0)

print(f"New Tensor: {z_unsqueeze}")
print(f"New Tensor Shape: {z_unsqueeze.shape}")

New Tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New Tensor Shape: torch.Size([1, 9])


In [ ]:
## You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims.

# Create tensor with specific shape

original_tensor = torch.rand(size=(224,224,3))

new_tensor = original_tensor.permute(2,0,1)   # shifts axis 0->1, 1->2, 2->0

print(original_tensor.shape)
print(new_tensor.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


**Indexing (selecting data from tensors)**

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

To do so, you can use indexing.

In [ ]:
# create a tensor

import torch
a = torch.arange(1,11)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
import torch
a1 = torch.arange(1,10).reshape(3,3)
a1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
import torch
a = torch.arange(1,10).reshape(1,3,3)
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
## Indexing values goes outer dimension -> inner dimension (check out the square brackets).

print(f"First square backet: {a[0]} ")

First square backet: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 


In [ ]:
print(f"Second square backet: {a[0][0]} ")

Second square backet: tensor([1, 2, 3]) 


In [ ]:
print(f"Third square backet: {a[0][0][0]} ")

Third square backet: 1 


In [ ]:
print(f"Third square backet: {a[0][1][0]} ")

Third square backet: 4 


In [ ]:
## You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.

z= torch.arange(1,10).reshape(1,3,3)
z

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension

z[:,0]

tensor([[1, 2, 3]])

In [ ]:
z[:,0,1]

tensor([2])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension

z[:,1,1]

tensor([5])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
## Z[dim0,dim1,dim2]

z[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension

# x[0][0]

z[0,0,:]

tensor([1, 2, 3])

**PyTorch tensors & NumPy**

Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The **two main methods** you'll want to use for NumPy to PyTorch (and back again) are:

**torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.**

**torch.Tensor.numpy() - PyTorch tensor -> NumPy array.**

In [ ]:
# Numpy array to tensor conversion

import torch
import numpy as np

array = np.arange(1,10)
tensor = torch.from_numpy(array)

print(array)
print(tensor)
print(array.dtype)
print(tensor.dtype)

[1 2 3 4 5 6 7 8 9]
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
int64
torch.int64


In [ ]:
tensor = torch.from_numpy(array).type(torch.float32)
print(tensor)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [ ]:
 # tensor to numpy array conversion

a = torch.arange(1,7)
num_array = a.numpy()
print(a.dtype)
print(num_array.dtype)
print(a)
print(num_array)

torch.int64
int64
tensor([1, 2, 3, 4, 5, 6])
[1 2 3 4 5 6]


**Reproducibility (trying to take the random out of random**)


In [ ]:
## create two random tensor

tensor_a = torch.rand(2,2)
tensor_b = torch.rand(2,2)

print(tensor_a)
print(tensor_b)

tensor_a == tensor_b

tensor([[0.1285, 0.8211],
        [0.3783, 0.4370]])
tensor([[0.5121, 0.2946],
        [0.8679, 0.5879]])


tensor([[False, False],
        [False, False]])

In [ ]:
##  But what if you wanted to created two random tensors with the same values.

## As in, the tensors would still contain random values but they would be of the same flavour.

## That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.


import random

random_seed = 42
torch.manual_seed(seed = random_seed)
tensor_c = torch.rand(3,3)
print(tensor_c)



torch.random.manual_seed(seed = random_seed)
tensor_d = torch.rand(3,3)
print(tensor_d)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])


In [ ]:
## Getting PyTorch to run on the GPU

# Check for GPU
import torch
torch.cuda.is_available()

False